name: 'Chrome extension version bump'
description: 'Update version number in version file '
inputs:
  path-to-version-file:
    description: 'The path to the version file'
    default: 'version.txt'
    required: true
  new-verison:
    description: 'Manually decide new version'
    required: false
  mode:
    description: 'Can be GET_VERSION, BUMP_VERSION, SET_VERSION'
    required: true
    default: 'BUMP_VERSION'
outputs:
  cur_ver:
    description: The current version
  new_ver:
    description: The new version
  was_bumped: 
    description: Whether the version was bumped or not
runs:
  using: 'node16'
  main: 'index.js'